In [3]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np


iris = load_iris()


df = pd.DataFrame(iris.data, columns=iris.feature_names)

df["species"] = pd.Categorical.from_codes(iris.target, iris.target_names)

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [5]:
mean_table = df.groupby("species" , observed=True).mean()

print("\nMEAN VALUES (Species-wise)\n")
mean_table.round(2)

MEAN VALUES (Species-wise)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
species,,,,
setosa,5.01,3.43,1.46,0.25
versicolor,5.94,2.77,4.26,1.33
virginica,6.59,2.97,5.55,2.03

In [7]:
std_table = df.groupby("species", observed=True).std()

print("\nSTANDARD DEVIATION (Species-wise)\n")
std_table.round(2)

STANDARD DEVIATION (Species-wise)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
species,,,,
setosa,0.35,0.38,0.17,0.11
versicolor,0.52,0.31,0.47,0.20
virginica,0.64,0.32,0.55,0.27

In [9]:
percentile_table = (
    df.groupby("species", observed=True)
      .quantile([0.25, 0.50, 0.75])
      .rename(index={0.25: "Q1 (25%)", 0.50: "Q2 (50%)", 0.75: "Q3 (75%)"})
)

print("\nPERCENTILE VALUES (Species-wise)\n")
percentile_table.round(2)

PERCENTILE VALUES (Species-wise)

                     sepal length (cm)  sepal width (cm)  petal length (cm)  \
species
setosa     Q1 (25%)               4.80              3.20               1.40
           Q2 (50%)               5.00              3.40               1.50
           Q3 (75%)               5.20              3.68               1.58
versicolor Q1 (25%)               5.60              2.52               4.00
           Q2 (50%)               5.90              2.80               4.35
           Q3 (75%)               6.30              3.00               4.60
virginica  Q1 (25%)               6.22              2.80               5.10
           Q2 (50%)               6.50              3.00               5.55
           Q3 (75%)               6.90              3.18               5.88

                     petal width (cm)
species
setosa     Q1 (25%)               0.2
           Q2 (50%)               0.2
           Q3 (75%)               0.3
versicolor Q1 (25%)               1.2
           Q2 (50%)               1.3
           Q3 (75%)               1.5
virginica  Q1 (25%)               1.8
           Q2 (50%)               2.0
           Q3 (75%)               2.3